version: 0.2

phases:
  pre_build:
    commands:
      - pip install --upgrade awscli
      - yarn

  build:
    commands:
      - yarn build

  post_build:
    commands:
      - ls -la
      - cd node_modules
      - ls -la

artifacts:
  files:
    - '**/*'