version: 0.2

phases:
  pre_build:
    commands:
      - pip install --upgrade awscli
      - npm install

  build:
    commands:
      - npm run build

  post_build:
    commands:
      - ls -la
      - cd node_modules
      - ls -la
      - cd ts-node/dist
      - ls -la

artifacts:
  files:
    - '**/*'